# general
ANALYSIS_MODE_0 0                # 線形弾性問題 (線形の解法): 0, 弾塑性問題 (updated lagrange, Newton Raphson法): 1
ANALYSIS_MODE_1 0                # 微小変形: 0, 有限変形: 1
BASE_PATCH_SIGA 0                # 結合剛性マトリクスの積分要素選択: ローカルパッチ 0, グローバルパッチ 1
SOLVER 4                         # solver PCG 0, GMRES 1, GaussianElimination 2, LU decomposition 3, sparse LU 4
M_MODE 2                         # 前処理行列のモード 0: M = K, 1: M = グローバルパッチとローカルパッチのKの対角バンド成分, 2: M = [[K^G, 0], [0, K^L]]
CALC_ON_GP 1                     # ガウス点での応力等の計算を行う 0, 行わない 1
CALC_ON_ELE_VERTEX 1             # 要素頂点での応力等の計算を行う 0, 行わない 1
OUTPUT_SVG 1                     # SVG 出力を行う 0, 行わない 1
OUTPUT_DEFORMED 0                # 変形後のメッシュ出力を行う 0, 行わない 1
PARAVIEW_GLO_MODE 0              # グローバルパッチで重ね合わせを行う 0, 行わない 1
PARAVIEW_CRACK_REPRESENTATION 1  # 亀裂がない場合 0, ある場合 1
BIN_MODE 2                       # paraview output file format, 0: text format, 1: binary format, 2: HDF5
MODE_EX 0                        # 一部で積分点数を増やして計算を行う 0, 行わない 1
MAX_OCTREE_N 0                   # OCTREE MESH の最大階層数, 積分で OCTREE MESH を使用しない場合 0
DM 1                             # 平面応力状態:DM = 0, 平面ひずみ状態:DM = 1
NG 4                             # Gauss-Legendreの積分点数
NG_EXTEND 8                      # Gauss-Legendreの拡張積分点数, (MODE_EX == 0 && ANALYSIS_MODE_0 == 0 の場合のみ有効)
BLENDING 0                       # blending function の適用 1, 適用しない 0

# B-bar method
B_BAR 0                          # B-bar method を使用しない 0, 使用する 1

# numerical parameters
EPS 1.0e-6                       # 連立1次方程式の残差

# nonlinear
TOTAL_SECONDS 1.0               # time
STEP_N 1                        # 非線形問題における荷重増分のステップ数
CUTBACK 1                       # 非線形問題における荷重増分の削減を行う 1, 行わない 0
NEWTON_RAPHSON_MAX_ITR  10       # 非線形問題におけるNewtonRaphson法の反復回数の上限
NEWTON_RAPHSON_EPS 1.0e-4        # 非線形問題におけるNewtonRaphson法の残差
UPDATE_CONTROL_POINT_MAX_ITR 100 # コントロールポイントの更新を行う場合の反復上限

# fictitious
FICT_COEF 1.0                # 架空領域の係数