# ==================================================
# Configuration File
# Note: Don't change key numbers [*]
# ==================================================

# [0] constant file
constant.ini

# [1] material file
material_ep_katayama.txt

# [2] crack_pair file
crack_pair_SIGA_no_crack.txt

# [3] load surface file

# [4] blending faces file
blending_faces_pipe.ini

# [5] auxiliary patch file
pipe_input_aux.txt

# [6] decreased order file (global)

# [7] decreased order file (local)