# constant file
constant.ini

# material file
material_elast.txt

# crack_pair file
crack_pair_SIGA_no_crack.txt

# load surface file
load_surface.txt

# blending faces file
blending_faces_cube_gakkai.ini

# blending faces file
../input/cube_gakkai_aux.txt