# curvature radius coefficient
1.0
# blending area [auxiliary patch num, direction (xi:0 or eta:1 or zeta:2), face (start:0 or end:1), area ratio]
0   0   0   1.0
1   0   0   1.0
1   2   0   1.0
2   2   0   1.0

# fictitious area [global patch num, xi start, xi end, eta start, eta end, zeta start, zeta end]
# 0   0.0 1.0   0.0 0.4   0.0 0.4