# constant file
constant.ini

# material file
material_plastic.txt

# crack_pair file
crack_pair.txt

# load surface file
load_surface.txt

# blending faces file
blending_faces.ini

# auxiliary patch file
../input/auxiliary_hole.txt