# constant file
constant.ini

# material file
material_WCCM.txt

# crack_pair file
crack_pair_SIGA.txt

# load surface file
load_surface.txt

# blending faces file
blending_faces_crack.ini

# auxiliary patch file
../input/auxiliary_crack.txt