# =========================================================
# General settings
# =========================================================
ANALYSIS_MODE 1                  # 解析モード: 0=平面応力(Plane stress), 1=平面ひずみ(Plane strain)
GEOMETRY_ONLY_OUTPUT 1           # 形状プレビューのみ出力 (解析を行わない): 0=無効, 1=有効
OUTPUT_GLOBAL_PARAMETERS 1       # グローバルの自然座標の出力OUTPUT_GLOBAL_PARAMETERS 1の時のみ可能: 0=無効, 1=有効
OUTPUT_PARAVIEW 1                # Paraview用の出力ファイルを生成: 0=無効, 1=有効
CALC_ON_GP 0                     # ガウス点での応力等の計算: 0=無効, 1=有効
CALC_ON_ELE_VERTEX 1             # 要素頂点での応力等の計算: 0=無効, 1=有効

# =========================================================
# Gaussian quadrature settings
# =========================================================
USE_EXTENDED_QUADRATURE 1        # 拡張ガウス積分を使用する: 0=無効, 1=有効
NUM_GAUSS_POINTS 4               # 通常の積分点数
NUM_GAUSS_POINTS_EXTENDED 10     # 拡張積分点数 (USE_EXTENDED_QUADRATURE=1 の場合に使用)

# =========================================================
# Fracture analysis settings
# =========================================================
FRACTURE_MODE 0             # 破壊力学解析を行う: 0=無効, 1=有効
CALCLATE_DISPLACEMENT 1     # 変位を計算する: 0=無効, 1=有効
INTEGRAL_DOMAIN_TYPE 5      # 破壊力学積分領域
CRACK_TYPE 0                # 亀裂作成種類: 0=フルモデル, 1=対称境界条件
OUTPUT_FREE_SURFACE 1       # 自由表面の出力: 0=無効, 1=有効
CRACK_LOAD 0                # 亀裂の荷重: 0=無効, 1=有効 // 未実装