#include <iostream>
#include <fstream>
#include <string>
#include <unordered_map>
#include <regex>
#include <vector>
#include <stack>
#include <filesystem>

namespace fs = std::filesystem;

class FileMerger {
private:
    std::unordered_map<std::string, std::string> constants;
    int dimension;

    std::string readFile(const std::string& filepath) {
        std::ifstream file(filepath);
        if (!file.is_open()) {
            throw std::runtime_error("Cannot open file: " + filepath);
        }

        std::string content;
        std::string line;
        while (std::getline(file, line)) {
            line.erase(std::remove(line.begin(), line.end(), '\r'), line.end());
            content += line + "\n";
        }
        return content;
    }

    void loadConstants(const std::string& constantFile) {
        std::ifstream file(constantFile);
        if (!file.is_open()) {
            throw std::runtime_error("Cannot open constant file: " + constantFile);
        }

        std::string key, value, line;
        while (std::getline(file, line)) {
            line.erase(std::remove(line.begin(), line.end(), '\r'), line.end());
            if (line.empty() || line[0] == '#') continue;

            std::istringstream iss(line);
            if (iss >> key >> value) {
                std::string key_info_c = "info->c." + key;
                constants[key_info_c] = value;
                std::cout << "Loaded constant: " << key_info_c << " = " << value << "\n";
            }
        }
    }

    std::vector<std::pair<size_t, size_t>> detectFunctionBlocks(const std::string& content) {
        std::vector<std::pair<size_t, size_t>> ignoreRanges;
        std::regex funcRegex(R"((Allocation|Get_Input_1)\s*\([^)]*\)\s*\{)");
        std::sregex_iterator it(content.begin(), content.end(), funcRegex);
        
        while (it != std::sregex_iterator()) {
            size_t start = it->position();
            size_t end = start;
            std::stack<char> braceStack;
            braceStack.push('{');

            for (size_t i = start + it->length(); i < content.size(); i++) {
                if (content[i] == '{') braceStack.push('{');
                else if (content[i] == '}') {
                    braceStack.pop();
                    if (braceStack.empty()) {
                        end = i;
                        break;
                    }
                }
            }

            if (!braceStack.empty()) {
                std::cerr << "Warning: Mismatched braces in function: " 
                         << content.substr(start, 50) << "...\n";
            }

            ignoreRanges.push_back({start, end});
            ++it;
        }

        return ignoreRanges;
    }

    std::string replaceConstants(std::string content) {
        std::vector<std::pair<size_t, size_t>> ignoreRanges = detectFunctionBlocks(content);
        bool replacementMade;
        
        do {
            replacementMade = false;
            
            for (const auto& [key, value] : constants) {
                std::regex pattern(R"(\b)" + key + R"(\b(?!\s*\())");
                std::sregex_iterator matchIt(content.begin(), content.end(), pattern);
                
                while (matchIt != std::sregex_iterator()) {
                    size_t matchStart = matchIt->position();
                    size_t matchEnd = matchStart + matchIt->length();
                    
                    bool shouldReplace = true;
                    for (const auto& range : ignoreRanges) {
                        if (matchStart >= range.first && matchEnd <= range.second) {
                            shouldReplace = false;
                            break;
                        }
                    }

                    if (shouldReplace) {
                        content.replace(matchStart, matchIt->length(), value);
                        replacementMade = true;
                    }
                    ++matchIt;
                }
            }
        } while (replacementMade);

        return content;
    }

public:
    void mergeFiles(const std::vector<std::string>& sourceFiles, 
                   const std::string& outputFile,
                   bool doReplacement = true) {
        std::ofstream out(outputFile);
        if (!out.is_open()) {
            throw std::runtime_error("Cannot create output file: " + outputFile);
        }

        out << "// Generated by FileMerger\n";
        out << "// Date: " << std::time(nullptr) << "\n";
        out << "// Replacement Mode: " << (doReplacement ? "ON" : "OFF") << "\n\n";

        for (const auto& file : sourceFiles) {
            try {
                std::cout << "Processing file: " << file << std::endl;
                std::string content = readFile(file);

                std::regex subHeaderRegex(R"(#include\s+\"_sub\.hpp\")");
                content = std::regex_replace(content, subHeaderRegex, "");

                if (doReplacement) {
                    content = replaceConstants(content);
                }

                out << "// Begin: " << fs::path(file).filename().string() << "\n";
                out << content << "\n";
                out << "// End: " << fs::path(file).filename().string() << "\n\n";
            }
            catch (const std::exception& e) {
                std::cerr << "Error processing " << file << ": " << e.what() << std::endl;
            }
        }
    }

    void setConstants(const std::string& constantFile, int dim) {
        loadConstants(constantFile);
        dimension = dim;
        constants["info->DIMENSION"] = std::to_string(dim);
        std::cout << "Set DIMENSION to: " << dim << "\n";
    }
};

int main(int argc, char* argv[]) {
    if (argc < 4) {
        std::cerr << "Usage: " << argv[0] 
                 << " constant.ini dimension source1.cpp [source2.cpp ...]\n";
        return 1;
    }

    try {
        std::string constantFile = argv[1];
        int dimension = std::stoi(argv[2]);
        std::vector<std::string> sourceFiles;

        for (int i = 3; i < argc; i++) {
            sourceFiles.push_back(argv[i]);
        }

        FileMerger merger;
        merger.setConstants(constantFile, dimension);
        
        // 置換ありのファイルを出力
        merger.mergeFiles(sourceFiles, "merged_output.cpp", true);
        
        // 置換なしのデバッグ用ファイルを出力
        merger.mergeFiles(sourceFiles, "merged_output_debug.cpp", false);

        std::cout << "Merge completed successfully.\n"
                 << "Output written to: merged_output.cpp\n"
                 << "Debug output written to: merged_output_debug.cpp" << std::endl;
    } 
    catch (const std::exception& e) {
        std::cerr << "Fatal error: " << e.what() << std::endl;
        return 1;
    }

    return 0;
}